server:
  # service startup port
  port: :9000

# drand api
drand:
  url:
    - "https://api.drand.secureweb3.com:6875"
    - "https://api.drand.sh/"
    - "https://api2.drand.sh/"
    - "https://api3.drand.sh/"
    - "https://drand.cloudflare.com/"
  chainHash: ""

mysql:
  url: localhost:3306
  username: root
  password: root

network:
  - id: 111
    name: puff-bob-jznbxtoq7h
    rpc: https://l2-puff-bob-jznbxtoq7h.t.conduit.xyz
    powerVotingAbi: /dist/power-voting.json
    powerVotingContract:
